{% set name = "pydaymet" %}
{% set version = "0.19.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: acc673db60fa2e63280c521ad934b70b059dfe2174fc2b7cd432e32cfb03563f

build:
  entry_points:
    - pydaymet = pydaymet.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - click >=0.7
    - netcdf4
    - numpy >=2
    - pandas >=1
    - pyproj >=3.0.1
    - rasterio
    - rioxarray >=0.15
    - shapely >=2
    - tiny-retriever >=0.1.3
    - xarray >=2024.7

test:
  imports:
    - pydaymet
  commands:
    - pip check
    - pydaymet --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hyriver/pydaymet
  summary: Access daily, monthly, and annual climate data via the Daymet web service.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
