{% set name = "pydaymet" %}
{% set version = "0.16.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: 5b8f3980ea4d2188ec2b95e08397492dd278cd5490247010be1a710825ea4719

build:
  entry_points:
    - pydaymet = pydaymet.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - async-retriever <0.17,>=0.16
    - click >=0.7
    - geopandas-base >=0.10
    - fiona
    - lxml
    - numpy >=1.21
    - pandas >=1.0
    - py3dep <0.17,>=0.16.1
    - pygeoogc <0.17,>=0.16.1
    - pygeoutils <0.17,>=0.16.1
    - pyproj >=3.0.1
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=2
    - xarray >=2023.01.0

test:
  imports:
    - pydaymet
  commands:
    - pip check
    - pydaymet --help
  requires:
    - pip

about:
  home: https://github.com/hyriver/pydaymet
  summary: Access daily, monthly, and annual climate data via the Daymet web service.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
