{% set name = "pydaymet" %}
{% set version = "0.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydaymet-{{ version }}.tar.gz
  sha256: 56973b592351b68f29353e9f0794e9b0b89ac2c6408754075e782d19a5d2e9ce

build:
  entry_points:
    - pydaymet = pydaymet.cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling >=1.12
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - aiofiles
    - aiohttp >=3.8.3
    - click >=0.7
    - numpy >=2
    - pandas >=1
    - pyproj >=3.0.1
    - rasterio >=1.2
    - rioxarray >=0.15
    - shapely >=2
    - xarray >=2024.7

test:
  imports:
    - pydaymet
  commands:
    - pip check
    - pydaymet --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hyriver/pydaymet
  summary: Access daily, monthly, and annual climate data via the Daymet web service.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
